services:
  - type: worker
    name: subito-telegram-bot
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
